[package]
name = "snowflakes"
version = "0.0.1"
authors = ["KennFatt <me@kennan.xyz>"]
edition = "2018"

[dependencies]
piston = "0.51.0"
piston_window = "0.110.0"
piston2d-graphics = "0.36.0"
piston2d-opengl_graphics = "0.72.0"
pistoncore-glutin_window = "0.65.0"

rand = "0.7.3"
